service: starter

variablesResolutionMode: 20210326

frameworkVersion: "3"

plugins:
  - serverless-webpack # must be the first of the list
  - serverless-offline # must be the last of the list

provider:
  name: aws
  runtime: nodejs20.x

functions:
  createLink:
    handler: ./src/apps/links/handlers/postLinks.main
    events:
    - http:
        path: links
        method: post
  
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: yarn # or npm
    includeModules: true